# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f905d72a84dd04568aefcc4aa86d12a42f1e4161045e4987dc5d89725717436b9b3c4083885ecee1059e9b5b07ed68b52d7dc96b9c71e2716420a3c1a7df8f8d

test:
  secret_key_base: bfd1a693594a46edf7c9636b04986e92d90782c173f32967971fa90bc28c22e79dc74a7ffa88b7a06b71d3cf8f42674f78718d05ffbcc7c41d44a6163b587980

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
